vich_uploader:
    db_driver: orm
    mappings:
        categorie_image:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            inject_on_load: true

